services:
  # Node.js Application
  nodejs-app:
    image: node:18-alpine
    container_name: nodejs-auth-api
    working_dir: /app
    volumes:
      - .:/app
    env_file: .env.development
    environment:
      POSTGRES_HOST: postgres-db
      MONGO_DB_URL_LOCAL: mongodb://mongo_user:mongo_password@mongo-db:27017/auth_db?authSource=admin
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
      - mongo-db
    command: sh -c "npm install && npm run dev"
    restart: unless-stopped

  # PostgreSQL Database
  postgres-db:
    image: postgres:14-alpine
    container_name: postgres-auth-api
    env_file: .env.development
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # MongoDB Database
  mongo-db:
    image: mongo:6
    container_name: mongo-auth-api
    env_file: .env.development
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-mongo_user}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-mongo_password}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME_LOCAL}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  # Database Management Tools (Optional)
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file: .env.development
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "5050:80"
    depends_on:
      - postgres-db
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    env_file: .env.development
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER:-mongo_user}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD:-mongo_password}
      ME_CONFIG_MONGODB_SERVER: mongo-db
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_USERNAME:-admin}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_PASSWORD:-admin}
    ports:
      - "8081:8081"
    depends_on:
      - mongo-db
    restart: unless-stopped

volumes:
  postgres_data:
  mongo_data: