version: '3.8'

services:
  # MongoDB Service
  mongo-db:
    image: mongo:6.0.6
    container_name: mongo-auth-api-dev
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo-user
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - mongo_data_dev:/data/db
    ports:
      - "27017:27017"

  # PostgreSQL Service
  postgres-db:
    image: postgres:latest
    container_name: postgres-auth-api-dev
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_LOCAL_PORT}:5432"

  # Your Node.js application (development mode)
  auth-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: auth-api-dev
    restart: always
    depends_on:
      - mongo-db
      - postgres-db
    env_file:
      - .env.development
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src  # For hot reloading
    ports:
      - "8000:8000"

volumes:
  mongo_data_dev:
  postgres_data_dev: